project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!session_1/slides/"
    - "!session_1/workshop/"
    - "!session_1/milestones/"
    - "!session_1/milestone-answers/"
  resources:
    - "files/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview:
    port: 4444

website:
  title: "2024 AYS Data Visualization"
  description: "Use R, ggplot2, and graphic design principles to tell powerful stories with data"
  site-url: "https://aysps.github.io/2024-aysps-dataviz-fall/"
  
  repo-url: "https://github.com/aysps/2024-aysps-dataviz-fall"
  # repo-actions: [edit, issue]
  
  navbar:
    background: "#0039A6"
    left:
      - href: session_1/index.qmd
        text: "Session I"
      - href: session_2/index.qmd
        text: "Session II"
      - href: session_3/index.qmd
        text: "Session III"
    right: 
      - href: "https://github.com/aysps/2024-aysps-dataviz-fall"
        icon: github
  
  page-footer:
    background: light
    left: |
      Content {{< fa brands creative-commons >}} 2024 by Andrew Heiss, Jason Coupet, and Virginia Carr Schneider <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} 
      [Creative Commons Attribution 4.0 International license (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/aysps/2024-aysps-dataviz-fall)

format:
  html:
    language: 
      title-block-author-single: "Instructor"
      title-block-published: "Date"
    shift-heading-level-by: 1
    theme:
      - zephyr
      - custom.scss
